-- AlterTable
ALTER TABLE `Community` ADD COLUMN `galleryCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `memberCount` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `CommunityMembership` ADD COLUMN `status` ENUM('PENDING', 'ACCEPTED', 'INVITED', 'BLOCKED') NOT NULL DEFAULT 'ACCEPTED';

-- AlterTable
ALTER TABLE `Gallery` ADD COLUMN `editPermission` ENUM('ADMIN', 'ANYONE') NOT NULL DEFAULT 'ADMIN',
    ADD COLUMN `memberCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `photoCount` INTEGER NOT NULL DEFAULT 0;
